### PR TITLE
Fix deploy.yaml

### PR DESCRIPTION
**Pull request by IAlibay**
Fixes #

Changes made in this Pull Request:
 - 

PR Checklist
------------
 - [ ] Tests?
 - [ ] Docs?
 - [ ] CHANGELOG updated?
 - [ ] Issue raised/referenced?

### CODE REVIEW

**Comment by IAlibay** [comment]
I'll add a test shim to check if it was just the quotes.

**Comment by IAlibay** [comment]
Ok that was it - looks like just quotes being a pain.

**Comment by lilyminium** [comment]
Thanks for the fix!

**Review by lilyminium — APPROVED** [review]

**Comment by lilyminium** [comment]
Worked like a charm, thank you @IAlibay!

**Pull request merged**
