### PR TITLE
Update deploy.yaml for OIDC

### PR DESCRIPTION
**Pull request by IAlibay**
Towards https://github.com/MDAnalysis/mdanalysis/issues/4326

### CODE REVIEW

**Comment by IAlibay** [comment]
PyPi & TestPyPi need configuring for trusted publishers

**Comment by lilyminium** [comment]
> PyPi & TestPyPi need configuring for trusted publishers

Hopefully just did this

**Comment by IAlibay** [comment]
Secrets have now been deleted - should be good to go.

**Review by lilyminium — APPROVED** [review]
LGTM then, thanks @IAlibay! I guess the only way to test is to actually make a release?

**Pull request merged**
