### PR TITLE
Change default theme option to gray

### LINKED ISSUE #59: Missing navigation menu on mobile website?
**Describe the bug**
It seems that the navigation menu is no longer accessible in the mobile version of the UserGuide.

**To Reproduce**
1. Go to https://userguide.mdanalysis.org/stable/index.html using a mobile device

**Expected behavior**
I expect to be able to access the navigation menu on mobile too, so that I can navigate the UserGuide.

**Actual behavior**
There is no navigation menu as far as I can tell, and therefore I have to rely on Google to land on the correct UserGuide page.

**Smartphone (please complete the following information):**
 - Device: iPhone SE
 - OS: iOS16
 - Browser: Safari/Firefox

### PR DESCRIPTION
**Pull request by lilyminium**
Fixes #59

Changes made in this Pull Request:
 - The `theme_style_nav_header_background` only seems to affect mobile layouts and its effect is hardcoded into `sphinx_rtd_theme` as inline CSS, privileging it over any style sheets. I've changed the default option to be gray for now.

PR Checklist
------------
 - [ ] Tests?
 - [ ] Docs?
 - [ ] CHANGELOG updated?
 - [ ] Issue raised/referenced?

### CODE REVIEW

**Comment by lilyminium** [comment]
Preview, just loaded:

Screenshot 2023-09-17 at 9 28 07 am

Preview, hamburger menu toggled:
Screenshot 2023-09-17 at 9 28 14 am

**Review by orbeckst — APPROVED** [review]
Thank you! Finally, I'll be able to see the menu on my phone. LGTM!

**Comment by lilyminium** [comment]
Thanks for the quick review @orbeckst!

**Comment by IAlibay** [comment]
Just looking at the RTD build here, I'm not sure this actually fixes things on chrome & android OS.

**Comment by lilyminium** [comment]
Sorry @IAlibay, I didn't update the options in the example docs -- opened #61 to update the demo docs.

**Pull request merged**
