### PR TITLE
Pin sphinx in setup.py

### PR DESCRIPTION
**Pull request by lilyminium**
Fixes #

Changes made in this Pull Request:
 - 

PR Checklist
------------
 - [ ] Tests?
 - [ ] Docs?
 - [ ] CHANGELOG updated?
 - [ ] Issue raised/referenced?

### CODE REVIEW

**Review by IAlibay — APPROVED** [review]
I thought it was already pinned upstream, any issue linked to the need for this?

**Comment by lilyminium** [comment]
It'd be nice to just install `mdanalysis-sphinx-theme` and leave the sphinx pinning to one central location here, instead of individual repos. `sphinx_rtd_theme` doesn't pin.

**Comment by IAlibay** [comment]
Is there a specific worry about something that will happen with 7.0 or is this "just in case"?

If it's the latter I'd actually encourage pinning in the conda-forge recipe rather than here. Generally, pins in pure source installs is kind of a pain - in the core library we just add the numpy upper pin at time of release, and even then it's because we know numpy 2.0 will be broken.

At the very minimum I would encourage having an issue to track this specific pin & a future where we will no longer pin.

**Comment by lilyminium** [comment]
We want pins for pip installs too though, right?
I raised https://github.com/MDAnalysis/mdanalysis-sphinx-theme/issues/71.

**Comment by IAlibay** [comment]
As mentioned above it's contentious because you're effectively blocking source installs at the same time. It's worth it if you know there's going to be an issue, but usually I'd do it just for the release and then unpin afterwards, that way your source install doesn't end up blocked.

**Comment by lilyminium** [comment]
I'm happy to unpin for those reasons but would definitely rather do it after the UGM -- I'm having sad visions of people doing pip installs for whatever reason (and from source, for whatever reason) and not being able to build docs at our hackathon!

**Comment by lilyminium** [comment]
Also happy to do it now if that future is unlikely to happen for technical or practical reasons in your opinion though?

**Comment by IAlibay** [comment]
No one is going to do a pip install from source right? I'd just unblock that assuming the pypi release happened already (unless you think you might have to do another release before the UGM?)

**Comment by lilyminium** [comment]
There's an issue now so there's no real harm in waiting though, right? New releases depend on if we find new issues and I guess installs from source depend on how enthusiastic people are about getting immediate fixes or modifying the theme themselves.

**Pull request merged**
